-- Creating table schema
 -- Create table departments

CREATE TABLE DEPARTMENTS 
	(DEPT_NO VARCHAR(10),
	DEPT_NAME VARCHAR(30) NOT NULL,
	PRIMARY KEY (DEPT_NO));

-- select * from departments
 -- Create table employees

CREATE TABLE EMPLOYEES 
	(EMP_NO INT NOT NULL,
	EMP_TITLE_ID VARCHAR(20) NOT NULL,
	BIRTH_DATE VARCHAR NOT NULL,
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	GENDER VARCHAR(2) NOT NULL,
	HIRE_DATE VARCHAR NOT NULL,
	FOREIGN KEY (EMP_TITLE_ID) REFERENCES TITLES (TITLE_ID));

-- select * from employees
 --Create table dept_emp

CREATE TABLE DEPT_EMP 
	(EMP_NO INT NOT NULL,
	DEPT_NO VARCHAR(10) NOT NULL,
	FOREIGN KEY (EMP_NO) REFERENCES SALARIES(EMP_NO),
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO));

-- select * from dept_emp
 -- Create table dept_managers

CREATE TABLE DEPT_MANAGERS 
	(DEPT_NO VARCHAR (10),
	EMP_NO INT,
	FOREIGN KEY (DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO),
	FOREIGN KEY (EMP_NO) REFERENCES SALARIES(EMP_NO));

-- select * from dept_managers
 --Creating salaries table

CREATE TABLE SALARIES 
	(EMP_NO BIGINT NOT NULL,
	SALARY BIGINT NOT NULL,
	PRIMARY KEY (EMP_NO));

-- select * from salaries
 --Creating titles table

CREATE TABLE TITLES 
	(TITLE_ID VARCHAR(20) NOT NULL,
	TITLE VARCHAR(20) NOT NULL,
	PRIMARY KEY(TITLE_ID));

-- select * from titles